### ISSUE TITLE
Set or update variables from github actions

### ISSUE THREAD

**Issue by YevheniiRybak** [tighten/laravel-deploy-preview#12]
Could you please implement setting or updating env variables from github actions?

```
on:
  pull_request:
    types: [opened, closed, push]
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tighten/laravel-deploy-preview@v1
        with:
          forge-token: ${{ secrets.FORGE_TOKEN }}
          servers: |
            ***** *****
          env:
              NEW_VAR: ${{ secrets.NEW_VAR }}
              ...
```
